[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "asyncio>=3.4.3",
    "flask>=3.1.0",
    "flask-cors>=5.0.1",
    "pydantic>=2.11.2",
]
